services:
  mongodb:
    image: mongo:7
    container_name: workflow_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - workflow_mongo_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: workflow_backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/workflowdb
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      AWS_REGION: ${AWS_REGION}
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: workflow_frontend
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - backend

  onlyoffice:
    image: onlyoffice/documentserver:latest
    container_name: workflow_onlyoffice
    restart: always
    ports:
      - "8082:80"
    environment:
      - JWT_ENABLED=false
    volumes:
      - workflow_onlyoffice_data:/var/www/onlyoffice/Data
      - workflow_onlyoffice_logs:/var/log/onlyoffice

volumes:
  workflow_mongo_data:
  workflow_onlyoffice_data:
  workflow_onlyoffice_logs: