spring.application.name=workflow-backend
server.port=8080
spring.data.mongodb.uri=mongodb://localhost:27017/workflowdb

# MinIO / S3
s3.access-key=${AWS_ACCESS_KEY_ID}
s3.secret-key=${AWS_SECRET_ACCESS_KEY}
s3.bucket-name=${AWS_S3_BUCKET_NAME}
s3.region=${AWS_REGION}