spring.application.name=workflow-backend
server.port=8080
spring.data.mongodb.uri=mongodb://localhost:27017/workflowdb

# AWS / S3
s3.access-key=${AWS_ACCESS_KEY_ID}
s3.secret-key=${AWS_SECRET_ACCESS_KEY}
s3.bucket-name=${AWS_S3_BUCKET_NAME}
s3.region=${AWS_REGION}

onlyoffice.document-server-url=http://localhost:8082
onlyoffice.backend-url=http://host.docker.internal:8080